#!/usr/bin/env julia

using Test

include(joinpath(@__DIR__, "benchmark_ce_green_matsubara_3x3.jl"))

@testset "CE OBC canonical physical-bond estimator" begin
    params = parse_args(String[
        "--lx=2", "--ly=2", "--boundary=open",
        "--nup=1", "--ndn=1", "--u=0.0",
        "--beta=2.0", "--dtau=0.1",
        "--nwarmups=0", "--batch-nsamples=1", "--max-batches=1",
        "--measure-interval=1", "--measure-greens=false", "--measure-bkt=false",
        "--measure-equal-time=true", "--measure-equal-time-correlations=true",
        "--use-charge-hs=false", "--force-symmetry=false", "--phase-reweight=false",
    ])
    system = build_system(params)
    qmc = build_qmc(system, params)
    walker = Walker(system, qmc)
    rho_up = DensityMatrix(system; Nft=qmc.num_FourierPoints)
    rho_dn = DensityMatrix(system; Nft=qmc.num_FourierPoints)
    ce_update_density_matrices!(system, walker, rho_up, rho_dn)
    geometry = build_square_geometry(2, 2; boundary="open")

    measured = measure_ce_obc_bond_observables(
        geometry, rho_up, rho_dn; U=0.0,
    )

    # Exact fixed-(Nup,Ndn) free-fermion trace for 2x2 OBC, beta=2,
    # Nup=Ndn=1. These values are independently generated by
    # obc_hubbard_ed.py, not by a Wick contraction of the projected 1-RDM.
    @test measured.kinetic_per_site ≈ -0.964027580075815 atol=5e-13
    @test measured.double_occupancy_per_site ≈ 0.0625 atol=5e-13
    @test measured.nn_spin ≈ -0.125 atol=5e-13
    @test measured.nn_charge_raw ≈ 0.125 atol=5e-13
    @test measured.nn_charge_connected ≈ -0.125 atol=5e-13
    @test measured.nnn_spin ≈ -0.125 atol=5e-13
    @test measured.nnn_charge_connected ≈ -0.125 atol=5e-13

    wrong_wick = SquareLatticeGeometry.measure_equal_time_observables(
        geometry, rho_up.ρ₁, rho_dn.ρ₁; U=0.0,
    )
    @test abs(wrong_wick.nn_spin - measured.nn_spin) > 1e-3
    @test abs(wrong_wick.nn_charge_connected - measured.nn_charge_connected) > 1e-3
end
